services:
  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    container_name: mini-inbox-frontend
    ports:
      - "3000:3000"
    environment:
      - INTERNAL_API_URL=http://backend:8000
      - NEXT_PUBLIC_API_URL=http://localhost:8000
    depends_on:
      - backend
    restart: unless-stopped

  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile
    container_name: mini-inbox-backend
    ports:
      - "8000:8000"
    volumes:
      - ../backend:/app
    command: uv run uvicorn app.main:app --host 0.0.0.0 --port 8000
    restart: unless-stopped

  n8n:
    image: docker.n8n.io/n8nio/n8n:2.31.5
    container_name: mini-inbox-n8n
    ports:
      - "5678:5678"
    environment:
      - N8N_HOST=localhost
      - N8N_PORT=5678
      - N8N_PROTOCOL=http
      - N8N_WEBHOOK_URL=http://localhost:5678/
      - GENERIC_TIMEZONE=America/Sao_Paulo
      - TZ=America/Sao_Paulo
    volumes:
      - n8n_data:/home/node/.n8n
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  n8n_data: